name: flutter_architecture_scaffold
description: flutter basic scaffold built with clean architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.1+3
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  flutter_bloc: ^6.0.6
  get_it: ^5.0.1
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
